services:
  orpheusmorebetter:
    image: ghcr.io/chodeus/orpheusmorebetter:main@sha256:ce1b4b64cddbef8a269d842ed67153bcd27e2d54baddd60e0f0c40f3bbc72795
    container_name: orpheusmorebetter
    hostname: orpheusmorebetter
    stdin_open: true
    tty: true
    environment:
      - PUID=99
      - PGID=100
      - UMASK=002
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - /path/to/your/data:/data/torrents
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: "no"
