services:
  orpheusmorebetter:
    image: ghcr.io/chodeus/orpheusmorebetter:main@sha256:d490d0ba80c7e8cafcdd13038f11d8abad5b420cab169f5630d01e77a80be1f4
    container_name: orpheusmorebetter
    hostname: orpheusmorebetter
    stdin_open: true
    tty: true
    environment:
      - PUID=99
      - PGID=100
      - UMASK=002
      - TZ=America/Los_Angeles
    volumes:
      - ./config:/config
      - /path/to/your/data:/data/torrents
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: "no"
