name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: chodeus/chodeus-ops/.github/workflows/release-please.yml@01955db8a3a9dfabfd1d0496db344ed42ea60753 # main
