name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: chodeus/chodeus-ops/.github/workflows/release-please.yml@bac8ae59708d42e8c3cd277fe1740164d0ec3ce0 # main
