name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: chodeus/chodeus-ops/.github/workflows/release-please.yml@bce9575d63bcd87ba1ff07bb95a08c64130104bd # main
